### ISSUE TITLE
cannot install on RHEL6.3

### ISSUE THREAD

**Issue by mateuszf** [iuscommunity-pkg/python35u#1]
Trying to install python35u on RHEL6.3 results in failed dependencies.
It requires openssl 1.0.1 which means that this package was built on RHEL6.5 or newer. It should be built on RHEL6.0 so dependency would be pointing to openssl 1.0.0

Console log:

```
yum install python35u
Loaded plugins: downloadonly, product-id, refresh-packagekit, security, subscription-manager
Updating certificate-based repositories.
Unable to read consumer identity
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package python35u.x86_64 0:3.5.0-2.ius.el6 will be installed
--> Processing Dependency: python35u-libs(x86-64) = 3.5.0-2.ius.el6 for package: python35u-3.5.0-2.ius.el6.x86_64
--> Processing Dependency: libpython3.5m.so.1.0()(64bit) for package: python35u-3.5.0-2.ius.el6.x86_64
--> Running transaction check
---> Package python35u-libs.x86_64 0:3.5.0-2.ius.el6 will be installed
--> Processing Dependency: libz.so.1(ZLIB_1.2.0)(64bit) for package: python35u-libs-3.5.0-2.ius.el6.x86_64
--> Processing Dependency: libssl.so.10(libssl.so.10)(64bit) for package: python35u-libs-3.5.0-2.ius.el6.x86_64
--> Processing Dependency: libcrypto.so.10(libcrypto.so.10)(64bit) for package: python35u-libs-3.5.0-2.ius.el6.x86_64
--> Processing Dependency: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit) for package: python35u-libs-3.5.0-2.ius.el6.x86_64
--> Processing Dependency: libcrypto.so.10(OPENSSL_1.0.1)(64bit) for package: python35u-libs-3.5.0-2.ius.el6.x86_64
--> Finished Dependency Resolution
Error: Package: python35u-libs-3.5.0-2.ius.el6.x86_64 (ius)
           Requires: libssl.so.10(libssl.so.10)(64bit)
Error: Package: python35u-libs-3.5.0-2.ius.el6.x86_64 (ius)
           Requires: libcrypto.so.10(OPENSSL_1.0.1)(64bit)
Error: Package: python35u-libs-3.5.0-2.ius.el6.x86_64 (ius)
           Requires: libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
Error: Package: python35u-libs-3.5.0-2.ius.el6.x86_64 (ius)
           Requires: libz.so.1(ZLIB_1.2.0)(64bit)
Error: Package: python35u-libs-3.5.0-2.ius.el6.x86_64 (ius)
           Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by carlwgeorge** [comment]
IUS only builds our packages against the latest base release.  RHEL 6.3 is terribly out of date (even if you paid for extended support from Red Hat).  Your system is quite vulnerable and I suggest you address that as soon as possible.

If you insist on staying on RHEL 6.3, feel free to [rebuild](https://wiki.centos.org/HowTos/RebuildSRPM) the [source RPM](https://dl.iuscommunity.org/pub/ius/stable/Redhat/6/SRPMS/python35u-3.5.0-2.ius.el6.src.rpm) yourself on that system, which will link it against the installed version of OpenSSL.

**Comment by mateuszf** [comment]
From what I understand libraries are backward compatible and package built on 6.0 can be used on any 6.x release, event the latest one with newest library versions.
So why build them only on latest release and effectively target them only for latest release ?

I know 6.3 is out of date I just happened to use it for tests, we actually build our software on much older 6.1 for 6.x branch so our clients can install it on basically any 6.x

**Comment by mateuszf** [comment]
Well nevermind, I can follow your advice and build it myself. Treat my previous comment as a loose thought. But please feel free to correct me if my understanding of backward compatiblity is wrong. Thanks for fast reply.

**Comment by carlwgeorge** [comment]
I'm afraid it's more complicated than that.  Here are the `libssl` provides from before and after the big OpenSSL update in RHEL 6.5.

```
libssl.so.10()(64bit)
```

```
libssl.so.10()(64bit)
libssl.so.10(OPENSSL_1.0.1)(64bit)
libssl.so.10(OPENSSL_1.0.1_EC)(64bit)
libssl.so.10(libssl.so.10)(64bit)
```

There is a notion of compatibility because the soname didn't change (`.so.10`), but there are also additional capabilities that are advertised.  When the RPM's are built, we don't have control over which capabilities it is linked against.  In this sense, it works more as "forward" compatibility than backwards (as you alluded to).

Even if we wanted to mitigate this by building on older releases, it would cause too many problems to be worth it.  OpenSSL libraries may have that "forward" compatibility, but many other system libraries don't.  A good example of that is ImageMagick; when it got updated in RHEL 6.7, the soname was bumped, and the php56u-pecl-imagick packages that were built on RHEL 6.6 [were not able to be cleanly installed on 6.7](https://github.com/iuscommunity-pkg/php56u-pecl-imagick/issues/1).  EPEL had to deal with [the same issue](https://bugzilla.redhat.com/show_bug.cgi?id=1248069).

I can't find it published anywhere, but EPEL has a similar approach to this as IUS.  EPEL is built against the latest bast release; you can use it on older releases if you choose to, but you are on your own if things don't work as expected.

**Comment by mateuszf** [comment]
It's still "backward" compatibility not "forward".

"backward" means that I can link on older version and have my binary working on newer version because libraries are backward compatible.
If package is built on 6.0 then it's linked against "libssl.so.10()(64bit)" and it's the job of distro maintainer to keep libraries backward compatible by providing the same set of libraries with the same set of capabilities as before and then some newer ones. Seems like on our example binary would be satisfied with it's "libssl.so.10()(64bit)" requirement.

"forward" would mean that ABI is frozen and no new libraries can be added in new releases because  "When the RPM's are built, we don't have control over which capabilities it is linked against.". That's our case and it's now working.

Example with "ImageMagick" means that Redhat did not keep their 6.x branch backwards compatible and fault was on their side.
Anyway I understand your decision of preferring 100% certainty that your package will be working on newest release but at the cost of backward compatibility.

**Comment by v6** [comment]
// , Does this mean that the `python35u` package might not work on CEntOS 6.5?

**Comment by b-harper** [comment]
@v6,  there are cases where IUS packages do work on older EL releases.  It is not recommended or supported.  Also note, EL 6.5 is EOL and I would recommend upgrading.

**Comment by v6** [comment]
// , Hm. I think it would be unwise to even stick with CEntOS 6.7 for more than a year longer, myself.

Would you recommend a Python 3 IUS package that would work with EL 6.3?

Perhaps python34u?

**Comment by b-harper** [comment]
@v6, I would recommend running current versions of CentOS and IUS packages.  If you are looking for IUS python packages from when EL 6.3 was current, you will need python33 from the archive repositories.  Our python34u packages came out after EL 6.3 went EOL.
